{
  "status": {
    "test_error": "cannot access local variable 'sys' where it is not associated with a value"
  },
  "examples": [],
  "metadata": {
    "error": "cannot access local variable 'sys' where it is not associated with a value",
    "traceback": "Traceback (most recent call last):\n  File \"/home/barberb/ipfs_accelerate_py/test/skills/test_hf_llama.py\", line 1420, in __test__\n    test_results = self.test()\n                   ^^^^^^^^^^^\n  File \"/home/barberb/ipfs_accelerate_py/test/skills/test_hf_llama.py\", line 1396, in test\n    \"python_version\": sys.version,\n                      ^^^\nUnboundLocalError: cannot access local variable 'sys' where it is not associated with a value\n"
  }
}